import { Dimension } from '../../domain/entities/dimension.entity';
import { DimensionOrmEntity } from './dimension.orm-entity';

export class DimensionMapper {
  static toDomain(orm: DimensionOrmEntity): Dimension {
    return Dimension.reconstitute(
      String(orm.id),
      orm.code,
      orm.name,
      orm.description,
      orm.order,
      orm.isActive,
    );
  }

  static toOrm(domain: Dimension): DimensionOrmEntity {
    const orm = new DimensionOrmEntity();
    // Only set ID if it's a valid number (for existing entities)
    // New entities will have their ID auto-generated by the database
    const numericId = Number(domain.id);
    if (!isNaN(numericId) && numericId > 0) {
      orm.id = numericId;
    }
    orm.code = domain.code;
    orm.name = domain.name;
    orm.description = domain.description;
    orm.order = domain.order;
    orm.isActive = domain.isActive;
    return orm;
  }
}
