import { Client } from '../../domain/entities/client.entity';
import { ClientOrmEntity } from './client.orm-entity';

export class ClientMapper {
  static toDomain(orm: ClientOrmEntity): Client {
    return Client.reconstitute(
      String(orm.id), // Convert ID numeric to string for domain
      orm.name,
      orm.createdAt,
      orm.updatedAt,
    );
  }

  static toOrm(domain: Client): ClientOrmEntity {
    const orm = new ClientOrmEntity();
    // Only set ID if it's a valid number (for existing entities)
    // New entities will have their ID auto-generated by the database
    const numericId = Number(domain.id);
    if (!isNaN(numericId) && numericId > 0) {
      orm.id = numericId;
    }
    orm.name = domain.name;
    orm.createdAt = domain.createdAt;
    orm.updatedAt = domain.updatedAt;
    return orm;
  }
}
