import { ActionPlan } from '../../domain/entities/action-plan.entity';
import { ActionPlanOrmEntity } from './action-plan.orm-entity';

export class ActionPlanMapper {
  static toDomain(orm: ActionPlanOrmEntity): ActionPlan {
    return ActionPlan.reconstitute(
      orm.uuid, // Use UUID for external identification
      String(orm.collaboratorId),
      orm.type,
      orm.description,
      orm.goals || [],
      orm.status,
      orm.createdAt,
      orm.updatedAt,
      orm.dueDate,
    );
  }

  static toOrm(domain: ActionPlan): ActionPlanOrmEntity {
    const orm = new ActionPlanOrmEntity();
    // Note: uuid is auto-generated by DB, don't set it when creating new records
    orm.uuid = domain.id;
    orm.collaboratorId = Number(domain.collaboratorId);
    orm.type = domain.type;
    orm.description = domain.description;
    orm.goals = domain.goals;
    orm.status = domain.status;
    orm.dueDate = domain.dueDate;
    orm.createdAt = domain.createdAt;
    orm.updatedAt = domain.updatedAt;
    return orm;
  }
}

