import { Injectable, Inject, Logger } from '@nestjs/common';
import type { IDimensionRepository } from '../../domain/repositories/dimension.repository.interface';
import { CreateDimensionCommand } from '../commands/create-dimension.command';
import { Dimension } from '../../domain/entities/dimension.entity';

@Injectable()
export class CreateDimensionUseCase {
  private readonly logger = new Logger(CreateDimensionUseCase.name);

  constructor(
    @Inject('IDimensionRepository')
    private readonly dimensionRepository: IDimensionRepository,
  ) {}

  async execute(command: CreateDimensionCommand): Promise<Dimension> {
    this.logger.log(`Creating dimension with code: ${command.code}`);

    // Check if code already exists
    const existingByCode = await this.dimensionRepository.findByCode(command.code);
    if (existingByCode) {
      throw new Error(`Dimension with code ${command.code} already exists`);
    }

    // Create dimension without ID - let the database generate it
    const dimension = Dimension.create(
      '', // Empty ID - will be auto-generated by database
      command.code,
      command.name,
      command.description,
      command.order,
      command.isActive,
    );

    await this.dimensionRepository.save(dimension);

    // Fetch the saved dimension to get the auto-generated ID
    const savedDimension = await this.dimensionRepository.findByCode(command.code);
    if (!savedDimension) {
      throw new Error('Failed to create dimension');
    }

    this.logger.log(`Dimension ${command.code} created successfully`);
    return savedDimension;
  }
}

