import { Injectable, Inject, Logger } from '@nestjs/common';
import { CreateTemplateCommand } from '../commands/create-template.command';
import type { IEvaluationTemplateRepository } from '../../domain/repositories/evaluation-template.repository.interface';
import { EvaluationTemplate } from '../../domain/entities/evaluation-template.entity';
import { Question } from '../../domain/entities/question.entity';

@Injectable()
export class CreateTemplateUseCase {
  private readonly logger = new Logger(CreateTemplateUseCase.name);

  constructor(
    @Inject('IEvaluationTemplateRepository')
    private readonly templateRepository: IEvaluationTemplateRepository,
  ) {}

  async execute(command: CreateTemplateCommand): Promise<EvaluationTemplate> {
    this.logger.log(
      `Creating template for milestone ${command.milestone}, role ${command.targetRole}`,
    );

    // Check if there's already an active template for this milestone and role
    const existingTemplate = await this.templateRepository.findActiveByMilestoneAndRole(
      command.milestone,
      command.targetRole,
    );

    if (existingTemplate) {
      this.logger.warn(
        `Active template already exists for milestone ${command.milestone}, role ${command.targetRole}. Consider updating instead.`,
      );
      // Optionally deactivate the existing one
      // For now, we'll allow multiple active templates but warn
    }

    // Create questions - IDs will be auto-generated by the database
    const questions = command.questions.map((q, index) =>
      Question.create(
        '', // Empty ID - will be auto-generated by database
        q.text,
        q.dimensionId,
        q.type,
        q.order || index + 1,
        q.required !== undefined ? q.required : true,
      ),
    );

    // Create template - ID will be auto-generated by the database
    const template = EvaluationTemplate.create(
      '', // Empty ID - will be auto-generated by database
      command.milestone,
      command.targetRole,
      command.title,
      command.description || null,
      questions,
      1, // First version
    );

    await this.templateRepository.save(template);

    // Fetch the saved template to get the auto-generated ID
    const savedTemplate = await this.templateRepository.findActiveByMilestoneAndRole(
      command.milestone,
      command.targetRole,
    );

    if (!savedTemplate) {
      throw new Error('Failed to retrieve saved template');
    }

    this.logger.log(`Template created with ID: ${savedTemplate.id}`);
    return savedTemplate;
  }
}
