import { Injectable, Inject, Logger } from '@nestjs/common';
import type { IDimensionRepository } from '../../domain/repositories/dimension.repository.interface';
import { Dimension } from '../../domain/entities/dimension.entity';

// Definición de las dimensiones ICER
const ICER_DIMENSIONS = [
  {
    code: 'INTEGRATION',
    name: 'Integración',
    description: 'Mide el nivel de integración del colaborador con el equipo y la organización',
    order: 1,
  },
  {
    code: 'COMMUNICATION',
    name: 'Comunicación',
    description: 'Evalúa la calidad de la comunicación del colaborador con el equipo y stakeholders',
    order: 2,
  },
  {
    code: 'ROLE_UNDERSTANDING',
    name: 'Entendimiento del Rol',
    description: 'Mide el entendimiento que tiene el colaborador de sus responsabilidades y funciones',
    order: 3,
  },
  {
    code: 'PERFORMANCE',
    name: 'Rendimiento',
    description: 'Evalúa el rendimiento y la productividad del colaborador en sus tareas',
    order: 4,
  },
];

@Injectable()
export class SeedDimensionsUseCase {
  private readonly logger = new Logger(SeedDimensionsUseCase.name);

  constructor(
    @Inject('IDimensionRepository')
    private readonly dimensionRepository: IDimensionRepository,
  ) {}

  async execute(): Promise<{ created: number; skipped: number; dimensions: Dimension[] }> {
    this.logger.log('Starting dimensions seed process');

    const dimensions: Dimension[] = [];
    let created = 0;
    let skipped = 0;

    for (const dimData of ICER_DIMENSIONS) {
      const existing = await this.dimensionRepository.findByCode(dimData.code);

      if (existing) {
        this.logger.log(`Dimension ${dimData.code} already exists, skipping`);
        dimensions.push(existing);
        skipped++;
        continue;
      }

      // Create dimension without ID - let the database generate it
      const dimension = Dimension.create(
        '', // Empty ID - will be auto-generated by database
        dimData.code,
        dimData.name,
        dimData.description,
        dimData.order,
        true,
      );

      await this.dimensionRepository.save(dimension);
      
      // Fetch the saved dimension to get the auto-generated ID
      const savedDimension = await this.dimensionRepository.findByCode(dimData.code);
      if (savedDimension) {
        dimensions.push(savedDimension);
      }
      
      created++;
      this.logger.log(`Dimension ${dimData.code} created`);
    }

    this.logger.log(`Dimensions seed completed: ${created} created, ${skipped} skipped`);
    return { created, skipped, dimensions };
  }
}
