import { Inject, Injectable, Logger } from '@nestjs/common';
import { IClientRepository } from '../../domain/repositories/client.repository.interface';
import { Client } from '../../domain/entities/client.entity';
import { CreateClientCommand } from '../commands/create-client.command';

@Injectable()
export class CreateClientUseCase {
  private readonly logger = new Logger(CreateClientUseCase.name);

  constructor(
    @Inject(IClientRepository)
    private readonly clientRepository: IClientRepository,
  ) {}

  async execute(command: CreateClientCommand): Promise<Client> {
    this.logger.log(`Creating client with name: ${command.name}`);

    // Check if client with same name already exists
    const existingClients = await this.clientRepository.findAll();
    const existingClient = existingClients.find(
      (c) => c.name.toLowerCase() === command.name.toLowerCase().trim(),
    );
    if (existingClient) {
      throw new Error('Client with this name already exists');
    }

    // ID will be auto-generated by database
    const client = Client.create('', command.name);

    const savedClient = await this.clientRepository.save(client);

    this.logger.log(`Client created successfully with ID: ${savedClient.id}`);
    return savedClient;
  }
}
