import { Collaborator } from '../../domain/entities/collaborator.entity';
import { CollaboratorOrmEntity } from './collaborator.orm-entity';

export class CollaboratorMapper {
  static toDomain(orm: CollaboratorOrmEntity): Collaborator {
    return Collaborator.reconstitute(
      orm.uuid, // Use UUID for external identification
      String(orm.id), // Internal numeric ID for FK relations
      orm.name,
      orm.email,
      orm.admissionDate,
      orm.project,
      orm.role,
      orm.teamLeader,
      String(orm.clientId),
      orm.status,
      orm.riskLevel,
      orm.createdAt,
      orm.updatedAt,
    );
  }

  static toOrm(domain: Collaborator): CollaboratorOrmEntity {
    const orm = new CollaboratorOrmEntity();
    // Note: uuid is auto-generated by DB, don't set it when creating new records
    orm.uuid = domain.id;
    orm.name = domain.name;
    orm.email = domain.email;
    orm.admissionDate = domain.admissionDate;
    orm.project = domain.project;
    orm.role = domain.role;
    orm.teamLeader = domain.teamLeader;
    orm.clientId = Number(domain.clientId);
    orm.status = domain.status;
    orm.riskLevel = domain.riskLevel;
    orm.createdAt = domain.createdAt;
    orm.updatedAt = domain.updatedAt;
    return orm;
  }
}
