import { User } from '../../domain/entities/user.entity';
import { UserOrmEntity } from './user.orm-entity';

export class UserMapper {
  static toDomain(orm: UserOrmEntity): User {
    return User.reconstitute(
      orm.uuid, // Use UUID for external identification
      orm.name,
      orm.email,
      orm.passwordHash,
      orm.role,
      orm.isActive,
      orm.createdAt,
      orm.updatedAt,
    );
  }

  static toOrm(domain: User): UserOrmEntity {
    const orm = new UserOrmEntity();
    // Note: uuid is auto-generated by DB, don't set it when creating new records
    orm.uuid = domain.id;
    orm.name = domain.name;
    orm.email = domain.email;
    orm.passwordHash = domain.passwordHash;
    orm.role = domain.role;
    orm.isActive = domain.isActive;
    orm.createdAt = domain.createdAt;
    orm.updatedAt = domain.updatedAt;
    return orm;
  }
}

